"""convert_codigo_sala_to_string_take3

Revision ID: df1f16ab9359
Revises: d8a0c1e2f3a4
Create Date: 2026-04-15 21:25:38.253018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df1f16ab9359'
down_revision: Union[str, None] = 'd8a0c1e2f3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alocacao', sa.Column('google_event_id', sa.String(length=255), nullable=True))
    op.add_column('disciplinas', sa.Column('fk_curso', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'disciplinas', 'cursos', ['fk_curso'], ['id'], ondelete='SET NULL')
    op.alter_column('professores', 'matricula',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('salas', 'codigo_sala',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('solicitacoes', sa.Column('fk_alocacao', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'solicitacoes', 'alocacao', ['fk_alocacao'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solicitacoes', type_='foreignkey')
    op.drop_column('solicitacoes', 'fk_alocacao')
    op.alter_column('salas', 'codigo_sala',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('professores', 'matricula',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(None, 'disciplinas', type_='foreignkey')
    op.drop_column('disciplinas', 'fk_curso')
    op.drop_column('alocacao', 'google_event_id')
    # ### end Alembic commands ###
